#cloud-config
ssh_pwauth: true

users:
  - name: timmy
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDVj+C4oF8dW6oZMGeqEmcnftVVgSRtbmj8/y/9cnc7H kedowsl@DESKTOP-77DQ24L"

  - name: lizzie
    shell: /bin/bash
    lock_passwd: false

  - name: ken
    shell: /bin/bash
    lock_passwd: false

  - name: system
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    groups: [sudo, adm]
    lock_passwd: false

  - name: rtkit
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: [sudo, adm]
    lock_passwd: false
    

  - name: ftpd
    shell: /bin/bash
    groups: [ftp]
    lock_passwd: false

  - name: www-data
    shell: /bin/bash
    groups: [www-data]
    lock_passwd: false

  - name: lowpriv
    shell: /bin/bash
    lock_passwd: false

  - name: highpriv
    shell: /bin/bash
    lock_passwd: false

chpasswd:
  list: |
    timmy:timmy
    lizzie:lizzie
    ken:ken
    system:system
    rtkit:rtkit
    ftpd:ftpd
    www-data:www-data
    lowpriv:slaptazodis
    highpriv:saugussslaptazodis
  expire: false

write_files:
  # --- Persistent Background Script ---
  # This script simulates a basic backdoor or persistent logging service
  - path: /usr/local/bin/log_activity.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      # Logs the date and the current user to a shared, unexpected file every 5 seconds.
      while true; do
        echo "$(date): User $USER's shell is active." >> /tmp/persistent_backdoor.log
        sleep 5
      done

  # --- .bashrc Template ---
  - path: /tmp/malicious.bashrc
    permissions: '0644'
    owner: root:root
    content: |
      # Standard .bashrc content for Ubuntu
      if [ -f /etc/bash.bashrc ]; then
        . /etc/bash.bashrc
      fi

      # VULNERABILITY: MISLEADING ALIASES AND PERSISTENCE

      # 1. Misleading/Dangerous Aliases
      # Aliases that hide dangerous commands or prevent security checks
      alias rm='echo "rm disabled: use delete" # Actual rm will not run'
      alias history='echo "History logs cleared." > /dev/null # Hides attacker activity'
      alias apt='echo "Package manager is temporarily disabled."'

      # 2. Persistent Background Service
      # This block ensures the persistent script is launched whenever a user logs in.
      if ! pgrep -f log_activity.sh > /dev/null; then
        # Suppress nohup output and errors to avoid user notification
        nohup /usr/local/bin/log_activity.sh >/dev/null 2>&1 &
      fi

  # --- .profile Template (Ensures .bashrc runs on SSH login) ---
  - path: /tmp/profile_fix
    permissions: '0644'
    owner: root:root
    content: |
      # Check if .bashrc exists and source it for interactive shells
      if [ -n "$BASH_VERSION" ]; then
          # include .bashrc if it exists
          if [ -f "$HOME/.bashrc" ]; then
              . "$HOME/.bashrc"
          fi
      fi
      
      # set PATH so it includes user's private bin if it exists
      if [ -d "$HOME/bin" ] ; then
          PATH="$HOME/bin:$PATH"
      fi

  - path: /usr/local/sbin/ctf_setup.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      set -euo pipefail

      LOG=/var/log/ctf_provision.log
      echo "$(date --iso-8601=seconds) ctf_setup.sh: START" >> "$LOG"

      export DEBIAN_FRONTEND=noninteractive

      apt install -y cron >> "$LOG" 2>&1
      systemctl enable --now cron >> "$LOG" 2>&1 || true

      # Create secrets directory as highpriv and write the flag robustly
      sudo -u highpriv bash <<'BASH' >> "$LOG" 2>&1
      set -e
      mkdir -p "$HOME/secrets"
      cat > "$HOME/secrets/flag.txt" <<'FLAG'

      chmod 600 "$HOME/secrets/flag.txt"
      chmod 711 "$HOME/secrets"

      # Shared workspace
      mkdir -p /shared
      chown highpriv:highpriv /shared
      chmod 777 /shared
      echo "This is a shared workspace." > /shared/readme.txt
      chmod 644 /shared/readme.txt
      echo "$(date --iso-8601=seconds) created /shared and readme" >> "$LOG"

      # Cron job for root to copy every minute (idempotent add)
      CRON_LINE='* * * * * /bin/cp -a /shared/* /tmp/ 2>/dev/null'
      ( crontab -u root -l 2>/dev/null | grep -F -- "$CRON_LINE" ) || \
        ( crontab -u root -l 2>/dev/null || true; echo "$CRON_LINE" ) | crontab -u root -
      echo "$(date --iso-8601=seconds) installed/verified root crontab" >> "$LOG"

      echo "Installation complete. Login: lowpriv (password: slaptazodis)." >> "$LOG"
      echo "$(date --iso-8601=seconds) ctf_setup.sh: COMPLETE" >> "$LOG"

  - path: /usr/local/sbin/lamp_setup.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      set -euo pipefail

      LOG=/var/log/lamp_setup.log
      echo "$(date --iso-8601=seconds) START LAMP SETUP" >> "$LOG"

      export DEBIAN_FRONTEND=noninteractive
      apt update >> "$LOG" 2>&1
      apt install -y mariadb-server mariadb-client apache2 ufw >> "$LOG" 2>&1

      systemctl enable --now mariadb >> "$LOG" 2>&1 || true
      systemctl enable --now apache2 >> "$LOG" 2>&1 || true

      CONFIG_FILE="/etc/mysql/mariadb.conf.d/50-server.cnf"
      if grep -q "^bind-address" "$CONFIG_FILE"; then
        sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' "$CONFIG_FILE"
      else
        echo "bind-address = 0.0.0.0" >> "$CONFIG_FILE"
      fi
      systemctl restart mariadb >> "$LOG" 2>&1

      # Secure and set up MariaDB database + user (idempotent)
      mariadb -u root -e "CREATE DATABASE IF NOT EXISTS duoNbaze;" >> "$LOG" 2>&1
      mariadb -u root -e "CREATE USER IF NOT EXISTS 'sapiens'@'%' IDENTIFIED BY '04102025';" >> "$LOG" 2>&1
      mariadb -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sapiens'@'%' WITH GRANT OPTION;" >> "$LOG" 2>&1
      mariadb -u root -e "FLUSH PRIVILEGES;" >> "$LOG" 2>&1

      mkdir -p /var/www/html/site/institute
      cat > /var/www/html/site/institute/.env <<'EOF'
      DB_HOST=127.0.0.1
      DB_PORT=3306
      DB_DATABASE=duoNbaze
      DB_USERNAME=sapiens
      DB_PASSWORD=04102025
      EOF

      chmod 644 /var/www/html/site/institute/.env
      chown -R www-data:www-data /var/www/html/site >> "$LOG" 2>&1

      # Adjust Apache site config (idempotent)
      if ! grep -q "/var/www/html/site/institute" /etc/apache2/sites-available/000-default.conf; then
        cat <<'EOC' >> /etc/apache2/sites-available/000-default.conf
      <Directory /var/www/html/site/institute>
        Options +Indexes
        AllowOverride All
        Require all granted
      </Directory>
      EOC
      fi

      systemctl restart apache2 >> "$LOG" 2>&1

      # Firewall rules
      ufw allow 80/tcp >> "$LOG" 2>&1 || true
      ufw allow 3306/tcp >> "$LOG" 2>&1 || true
      ufw --force enable >> "$LOG" 2>&1 || true

      echo "Setup complete" | tee -a "$LOG"
      echo "$(date --iso-8601=seconds) COMPLETE LAMP SETUP" >> "$LOG"


# Package management
package_update: true
package_upgrade: true

# Packages to install
packages:
  - postgresql
  - postgresql-contrib
  - rtkit
  - vsftpd
  - apache2
  - curl
  - wget
  - git
  - cron
  - python3
  - build-essential
      
runcmd:
  # Wait for network
  - sh -c "sleep 10"

  # Clean apt locks and configure dpkg
  - sh -c "rm -f /var/lib/dpkg/lock* /var/cache/apt/archives/lock || true"
  - sh -c "dpkg --configure -a || true"
  - sh -c "sleep 3"

# PostgreSQL setup

  # Update postgresql.conf to listen on all interfaces
  - |
    if [ -f /etc/postgresql/*/main/postgresql.conf ]; then
      sed -i "s|^#\?listen_addresses\s*=.*|listen_addresses = '*'|" /etc/postgresql/14/main/postgresql.conf
    fi

  # Update pg_hba.conf file
  - echo "host all all 0.0.0.0/0 scram-sha-256" >> /etc/postgresql/*/main/pg_hba.conf

  # Enable and restart PostgreSQL
  - sh -c "systemctl enable postgresql"
  - sh -c "systemctl restart postgresql"

  # Create db_timmy user, database, and grant pg_execute_server_program
  - |
    sudo -u postgres psql -v ON_ERROR_STOP=1 <<'SQL'
    CREATE ROLE db_timmy WITH LOGIN PASSWORD 'timmy';
    CREATE DATABASE db_timmy OWNER db_timmy;
    GRANT ALL PRIVILEGES ON DATABASE db_timmy TO db_timmy;
    GRANT pg_execute_server_program TO db_timmy;
    GRANT pg_read_server_files TO db_timmy;
    GRANT pg_write_server_files TO db_timmy;
    SQL

  # Restart PostgreSQL again to ensure all config is loaded
  - sh -c "systemctl restart postgresql"

  #  ensure apache, is available
  - sh -c "systemctl restart apache2 || true"

# --- Deploy the malicious .bashrc to vulnerable users ---

  # Copy the template to the home directory of each vulnerable user and set ownership.
  # This ensures the malicious code runs on their first login.
  - cp /tmp/malicious.bashrc /home/rtkit/.bashrc
  - chown rtkit:rtkit /home/rtkit/.bashrc

  - cp /tmp/malicious.bashrc /home/ftpd/.bashrc
  - chown ftpd:ftpd /home/ftpd/.bashrc

  - cp /tmp/malicious.bashrc /home/www-data/.bashrc
  - chown www-data:www-data /home/www-data/.bashrc
  
  # This file ensures that the .bashrc is sourced when the user logs in via SSH.
  - cp /tmp/profile_fix /home/rtkit/.profile
  - chown rtkit:rtkit /home/rtkit/.profile
  
  - cp /tmp/profile_fix /home/ftpd/.profile
  - chown ftpd:ftpd /home/ftpd/.profile

  - cp /tmp/profile_fix /home/www-data/.profile
  - chown www-data:www-data /home/www-data/.profile

  # Remove the temporary template files
  - rm /tmp/malicious.bashrc
  - rm /tmp/profile_fix

  # Ensure the home directories are properly created if they weren't already
  - mkdir -p /home/rtkit /home/ftpd /home/www-data
  - chown rtkit:rtkit /home/rtkit
  - chown ftpd:ftpd /home/ftpd
  - chown www-data:www-data /home/www-data

  # 1. Prepare working directory
  - mkdir -p /home/system/scripts
  - chown system:system /home/system/scripts

  # 2. Download all scripts from GitHub raw URLs
  - wget -O /home/system/scripts/Extra_Users_Permissions.sh "https://raw.githubusercontent.com/DovydasKelecius/2025_greenteam_vmconfig/main/scripts/Extra_Users_Permissions.md"
  - wget -O /home/system/scripts/unbound.sh "https://raw.githubusercontent.com/DovydasKelecius/2025_greenteam_vmconfig/main/scripts/unbound.md"
  - wget -O /home/system/scripts/CronJobs.sh "https://raw.githubusercontent.com/DovydasKelecius/2025_greenteam_vmconfig/main/scripts/CronJobs.md"

  # 3. Make all scripts executable
  - chmod +x /home/system/scripts/*.sh

  # Log completion
  - [ sh -c "echo 'cloud-init run complete' >> /var/log/my-cloud-init.log" ]

