#cloud-config
ssh_pwauth: true

users:
  - name: timmy
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDVj+C4oF8dW6oZMGeqEmcnftVVgSRtbmj8/y/9cnc7H kedowsl@DESKTOP-77DQ24L"

  - name: lizzie
    shell: /bin/bash
    lock_passwd: false

  - name: ken
    shell: /bin/bash
    lock_passwd: false

  - name: system
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    groups: [sudo, adm]
    lock_passwd: false

  - name: rtkit
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: [sudo, adm]
    lock_passwd: false
    

  - name: ftpd
    shell: /bin/bash
    groups: [ftp]
    lock_passwd: false

  - name: www-data
    shell: /bin/bash
    groups: [www-data]
    lock_passwd: false

  - name: lowpriv
    shell: /bin/bash
    lock_passwd: false

  - name: highpriv
    shell: /bin/bash
    lock_passwd: false

chpasswd:
  list: |
    timmy:timmy
    lizzie:lizzie
    ken:ken
    system:system
    rtkit:rtkit
    ftpd:ftpd
    www-data:www-data
    lowpriv:slaptazodis
    highpriv:saugussslaptazodis
  expire: false

write_files:
  # --- Persistent Background Script ---
  # This script simulates a basic backdoor or persistent logging service
  - path: /usr/local/bin/log_activity.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      # Logs the date and the current user to a shared, unexpected file every 5 seconds.
      while true; do
        echo "$(date): User $USER's shell is active." >> /tmp/persistent_backdoor.log
        sleep 5
      done

  # --- .bashrc Template ---
  - path: /tmp/malicious.bashrc
    permissions: '0644'
    owner: root:root
    content: |
      # Standard .bashrc content for Ubuntu
      if [ -f /etc/bash.bashrc ]; then
        . /etc/bash.bashrc
      fi

      # VULNERABILITY: MISLEADING ALIASES AND PERSISTENCE

      # 1. Misleading/Dangerous Aliases
      # Aliases that hide dangerous commands or prevent security checks
      alias rm='echo "rm disabled: use delete" # Actual rm will not run'
      alias history='echo "History logs cleared." > /dev/null # Hides attacker activity'
      alias apt='echo "Package manager is temporarily disabled."'

      # 2. Persistent Background Service
      # This block ensures the persistent script is launched whenever a user logs in.
      if ! pgrep -f log_activity.sh > /dev/null; then
        # Suppress nohup output and errors to avoid user notification
        nohup /usr/local/bin/log_activity.sh >/dev/null 2>&1 &
      fi

  # --- .profile Template (Ensures .bashrc runs on SSH login) ---
  - path: /tmp/profile_fix
    permissions: '0644'
    owner: root:root
    content: |
      # Check if .bashrc exists and source it for interactive shells
      if [ -n "$BASH_VERSION" ]; then
          # include .bashrc if it exists
          if [ -f "$HOME/.bashrc" ]; then
              . "$HOME/.bashrc"
          fi
      fi
      
      # set PATH so it includes user's private bin if it exists
      if [ -d "$HOME/bin" ] ; then
          PATH="$HOME/bin:$PATH"
      fi


# Package management
package_update: true
package_upgrade: true

# Packages to install
packages:
  - postgresql
  - postgresql-contrib
  - rtkit
  - vsftpd
  - apache2
  - git
      
runcmd:
  # Wait for network
  - sh -c "sleep 10"

  # Clean apt locks and configure dpkg
  - sh -c "rm -f /var/lib/dpkg/lock* /var/cache/apt/archives/lock || true"
  - sh -c "dpkg --configure -a || true"
  - sh -c "sleep 3"

# PostgreSQL setup

  # Update postgresql.conf to listen on all interfaces
  - |
    if [ -f /etc/postgresql/*/main/postgresql.conf ]; then
      sed -i "s|^#\?listen_addresses\s*=.*|listen_addresses = '*'|" /etc/postgresql/14/main/postgresql.conf
    fi

  # Update pg_hba.conf file
  - echo "host all all 0.0.0.0/0 scram-sha-256" >> /etc/postgresql/*/main/pg_hba.conf

  # Enable and restart PostgreSQL
  - sh -c "systemctl enable postgresql"
  - sh -c "systemctl restart postgresql"

  # Create db_timmy user, database, and grant pg_execute_server_program
  - |
    sudo -u postgres psql -v ON_ERROR_STOP=1 <<'SQL'
    CREATE ROLE db_timmy WITH LOGIN PASSWORD 'timmy';
    CREATE DATABASE db_timmy OWNER db_timmy;
    GRANT ALL PRIVILEGES ON DATABASE db_timmy TO db_timmy;
    GRANT pg_execute_server_program TO db_timmy;
    GRANT pg_read_server_files TO db_timmy;
    GRANT pg_write_server_files TO db_timmy;
    SQL

  # Restart PostgreSQL again to ensure all config is loaded
  - sh -c "systemctl restart postgresql"

  #  ensure apache, is available
  - sh -c "systemctl restart apache2 || true"

# --- Deploy the malicious .bashrc to vulnerable users ---

  # Copy the template to the home directory of each vulnerable user and set ownership.
  # This ensures the malicious code runs on their first login.
  - cp /tmp/malicious.bashrc /home/rtkit/.bashrc
  - chown rtkit:rtkit /home/rtkit/.bashrc

  - cp /tmp/malicious.bashrc /home/ftpd/.bashrc
  - chown ftpd:ftpd /home/ftpd/.bashrc

  - cp /tmp/malicious.bashrc /home/www-data/.bashrc
  - chown www-data:www-data /home/www-data/.bashrc
  
  # This file ensures that the .bashrc is sourced when the user logs in via SSH.
  - cp /tmp/profile_fix /home/rtkit/.profile
  - chown rtkit:rtkit /home/rtkit/.profile
  
  - cp /tmp/profile_fix /home/ftpd/.profile
  - chown ftpd:ftpd /home/ftpd/.profile

  - cp /tmp/profile_fix /home/www-data/.profile
  - chown www-data:www-data /home/www-data/.profile

  # Remove the temporary template files
  - rm /tmp/malicious.bashrc
  - rm /tmp/profile_fix

  # Ensure the home directories are properly created if they weren't already
  - mkdir -p /home/rtkit /home/ftpd /home/www-data
  - chown rtkit:rtkit /home/rtkit
  - chown ftpd:ftpd /home/ftpd
  - chown www-data:www-data /home/www-data


  # Run the Justas1 permission script
  - echo 'Justas1 - Start' >> /var/log/my-cloud-init.log

  - sh -c "bash /usr/local/sbin/Justas1.sh >> /var/log/my-cloud-init.log 2>&1 || echo 'Justas1 script encountered an error' >> /var/log/my-cloud-init.log"
  - echo 'Justas1 - End' >> /var/log/my-cloud-init.log

  - sh -c "echo 'Gali buti jog viskas gerai susinstaliavosi (arba ne), prisijungimo vardas - lowpriv (slaptazodis - slaptazodis).' >> /var/log/my-cloud-init.log"

  # Log completion
  - [ sh -c "echo 'cloud-init run complete' >> /var/log/my-cloud-init.log" ]
